### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by dokwon** [terra-project/research#1]
@nplatias could we update the readme for this page? The simulation model doc on quip, or some summarized version thereof should be helpful.

Also a high level breakdown on what simulations are available, what the inputs are etc would be helpful also.

**Comment by dokwon** [comment]
Reminder on this!

**Comment by nplatias** [comment]
@dokwon sorry for missing this. Re-organizing the research repo this week and will add a detailed outline, instructions on running things etc

**Comment by dokwon** [comment]
Done.
